# Generated by Django 6.1 on 2026-08-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
            options={
                'verbose_name': 'Etiqueta de estado',
                'verbose_name_plural': 'Etiquetas de estado',
            },
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
            options={
                'verbose_name': 'Etiqueta de importancia',
                'verbose_name_plural': 'Etiquetas de importancia',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField(verbose_name='fecha límite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estado')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.importancia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
