# Generated by Django 6.1 on 2026-08-11 02:33

from django.db import migrations

def crear_estados(apps, schema_editor):
    r""" Crea los estados iniciales del modelo `actividades.Estado` """
    Estado = apps.get_model('actividades', 'Estado')
    Estado.objects.get_or_create(titulo='Creada')
    Estado.objects.get_or_create(titulo='En progreso')
    Estado.objects.get_or_create(titulo='Terminada')
    Estado.objects.get_or_create(titulo='Cancelada')

def crear_importancias(apps, schema_editor):
    r""" Crea las importancias iniciales del modelo `actividades.Importancia` """
    Importancia = apps.get_model('actividades', 'Importancia')
    Importancia.objects.get_or_create(titulo='Baja')
    Importancia.objects.get_or_create(titulo='Media')
    Importancia.objects.get_or_create(titulo='Alta')


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_estados),
        migrations.RunPython(crear_importancias),
    ]

